/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as publicIndexRouteImport } from './../../routes/(public)/index'
import { Route as publicRegisterRouteImport } from './../../routes/(public)/register'
import { Route as publicContactRouteImport } from './../../routes/(public)/contact'
import { Route as publicAboutRouteImport } from './../../routes/(public)/about'
import { Route as dashboardPortalRouteImport } from './../../routes/(dashboard)/portal'
import { Route as dashboardDashboardRouteImport } from './../../routes/(dashboard)/dashboard'
import { Route as adminTransportRouteImport } from './../../routes/(admin)/transport'
import { Route as adminTaxpayersRouteImport } from './../../routes/(admin)/taxpayers'
import { Route as adminServicesRouteImport } from './../../routes/(admin)/services'
import { Route as adminSanitationRouteImport } from './../../routes/(admin)/sanitation'
import { Route as adminRevenueCenterRouteImport } from './../../routes/(admin)/revenue-center'
import { Route as adminReportsRouteImport } from './../../routes/(admin)/reports'
import { Route as adminPaymentsRouteImport } from './../../routes/(admin)/payments'
import { Route as adminNotificationsRouteImport } from './../../routes/(admin)/notifications'
import { Route as adminNoticesRouteImport } from './../../routes/(admin)/notices'
import { Route as adminMarketsRouteImport } from './../../routes/(admin)/markets'
import { Route as adminIntelligenceRouteImport } from './../../routes/(admin)/intelligence'
import { Route as adminGisRouteImport } from './../../routes/(admin)/gis'
import { Route as adminExecutiveRouteImport } from './../../routes/(admin)/executive'
import { Route as adminComplianceRouteImport } from './../../routes/(admin)/compliance'
import { Route as adminCommandCenterRouteImport } from './../../routes/(admin)/command-center'
import { Route as adminBylawsRouteImport } from './../../routes/(admin)/bylaws'
import { Route as adminBusinessesRouteImport } from './../../routes/(admin)/businesses'
import { Route as publicPropertiesIndexRouteImport } from './../../routes/(public)/properties.index'
import { Route as dashboardOfficerIndexRouteImport } from './../../routes/(dashboard)/officer/index'
import { Route as dashboardMarshalIndexRouteImport } from './../../routes/(dashboard)/marshal/index'
import { Route as ApiPublicSeedDemoRouteImport } from './../../routes/api/public/seed-demo'
import { Route as publicPropertiesRegisterRouteImport } from './../../routes/(public)/properties.register'
import { Route as authAuthSignupRouteImport } from './../../routes/(auth)/auth.signup'
import { Route as authAuthLoginRouteImport } from './../../routes/(auth)/auth.login'
import { Route as adminMarketsTradersRouteImport } from './../../routes/(admin)/markets.traders'
import { Route as adminMarketsRegisterRouteImport } from './../../routes/(admin)/markets.register'
import { Route as adminMarketsCollectRouteImport } from './../../routes/(admin)/markets.collect'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRegisterRoute = publicRegisterRouteImport.update({
  id: '/(public)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicContactRoute = publicContactRouteImport.update({
  id: '/(public)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/(public)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardPortalRoute = dashboardPortalRouteImport.update({
  id: '/(dashboard)/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const adminTransportRoute = adminTransportRouteImport.update({
  id: '/(admin)/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const adminTaxpayersRoute = adminTaxpayersRouteImport.update({
  id: '/(admin)/taxpayers',
  path: '/taxpayers',
  getParentRoute: () => rootRouteImport,
} as any)
const adminServicesRoute = adminServicesRouteImport.update({
  id: '/(admin)/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSanitationRoute = adminSanitationRouteImport.update({
  id: '/(admin)/sanitation',
  path: '/sanitation',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRevenueCenterRoute = adminRevenueCenterRouteImport.update({
  id: '/(admin)/revenue-center',
  path: '/revenue-center',
  getParentRoute: () => rootRouteImport,
} as any)
const adminReportsRoute = adminReportsRouteImport.update({
  id: '/(admin)/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const adminPaymentsRoute = adminPaymentsRouteImport.update({
  id: '/(admin)/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const adminNotificationsRoute = adminNotificationsRouteImport.update({
  id: '/(admin)/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const adminNoticesRoute = adminNoticesRouteImport.update({
  id: '/(admin)/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const adminMarketsRoute = adminMarketsRouteImport.update({
  id: '/(admin)/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const adminIntelligenceRoute = adminIntelligenceRouteImport.update({
  id: '/(admin)/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const adminGisRoute = adminGisRouteImport.update({
  id: '/(admin)/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const adminExecutiveRoute = adminExecutiveRouteImport.update({
  id: '/(admin)/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const adminComplianceRoute = adminComplianceRouteImport.update({
  id: '/(admin)/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const adminCommandCenterRoute = adminCommandCenterRouteImport.update({
  id: '/(admin)/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const adminBylawsRoute = adminBylawsRouteImport.update({
  id: '/(admin)/bylaws',
  path: '/bylaws',
  getParentRoute: () => rootRouteImport,
} as any)
const adminBusinessesRoute = adminBusinessesRouteImport.update({
  id: '/(admin)/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPropertiesIndexRoute = publicPropertiesIndexRouteImport.update({
  id: '/(public)/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOfficerIndexRoute = dashboardOfficerIndexRouteImport.update({
  id: '/(dashboard)/officer/',
  path: '/officer/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardMarshalIndexRoute = dashboardMarshalIndexRouteImport.update({
  id: '/(dashboard)/marshal/',
  path: '/marshal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPropertiesRegisterRoute =
  publicPropertiesRegisterRouteImport.update({
    id: '/(public)/properties/register',
    path: '/properties/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/(auth)/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/(auth)/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const adminMarketsTradersRoute = adminMarketsTradersRouteImport.update({
  id: '/traders',
  path: '/traders',
  getParentRoute: () => adminMarketsRoute,
} as any)
const adminMarketsRegisterRoute = adminMarketsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => adminMarketsRoute,
} as any)
const adminMarketsCollectRoute = adminMarketsCollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => adminMarketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/businesses': typeof adminBusinessesRoute
  '/bylaws': typeof adminBylawsRoute
  '/command-center': typeof adminCommandCenterRoute
  '/compliance': typeof adminComplianceRoute
  '/executive': typeof adminExecutiveRoute
  '/gis': typeof adminGisRoute
  '/intelligence': typeof adminIntelligenceRoute
  '/markets': typeof adminMarketsRouteWithChildren
  '/notices': typeof adminNoticesRoute
  '/notifications': typeof adminNotificationsRoute
  '/payments': typeof adminPaymentsRoute
  '/reports': typeof adminReportsRoute
  '/revenue-center': typeof adminRevenueCenterRoute
  '/sanitation': typeof adminSanitationRoute
  '/services': typeof adminServicesRoute
  '/taxpayers': typeof adminTaxpayersRoute
  '/transport': typeof adminTransportRoute
  '/dashboard': typeof dashboardDashboardRoute
  '/portal': typeof dashboardPortalRoute
  '/about': typeof publicAboutRoute
  '/contact': typeof publicContactRoute
  '/register': typeof publicRegisterRoute
  '/': typeof publicIndexRoute
  '/markets/collect': typeof adminMarketsCollectRoute
  '/markets/register': typeof adminMarketsRegisterRoute
  '/markets/traders': typeof adminMarketsTradersRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/properties/register': typeof publicPropertiesRegisterRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/marshal/': typeof dashboardMarshalIndexRoute
  '/officer/': typeof dashboardOfficerIndexRoute
  '/properties/': typeof publicPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/businesses': typeof adminBusinessesRoute
  '/bylaws': typeof adminBylawsRoute
  '/command-center': typeof adminCommandCenterRoute
  '/compliance': typeof adminComplianceRoute
  '/executive': typeof adminExecutiveRoute
  '/gis': typeof adminGisRoute
  '/intelligence': typeof adminIntelligenceRoute
  '/markets': typeof adminMarketsRouteWithChildren
  '/notices': typeof adminNoticesRoute
  '/notifications': typeof adminNotificationsRoute
  '/payments': typeof adminPaymentsRoute
  '/reports': typeof adminReportsRoute
  '/revenue-center': typeof adminRevenueCenterRoute
  '/sanitation': typeof adminSanitationRoute
  '/services': typeof adminServicesRoute
  '/taxpayers': typeof adminTaxpayersRoute
  '/transport': typeof adminTransportRoute
  '/dashboard': typeof dashboardDashboardRoute
  '/portal': typeof dashboardPortalRoute
  '/about': typeof publicAboutRoute
  '/contact': typeof publicContactRoute
  '/register': typeof publicRegisterRoute
  '/': typeof publicIndexRoute
  '/markets/collect': typeof adminMarketsCollectRoute
  '/markets/register': typeof adminMarketsRegisterRoute
  '/markets/traders': typeof adminMarketsTradersRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/properties/register': typeof publicPropertiesRegisterRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/marshal': typeof dashboardMarshalIndexRoute
  '/officer': typeof dashboardOfficerIndexRoute
  '/properties': typeof publicPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)/businesses': typeof adminBusinessesRoute
  '/(admin)/bylaws': typeof adminBylawsRoute
  '/(admin)/command-center': typeof adminCommandCenterRoute
  '/(admin)/compliance': typeof adminComplianceRoute
  '/(admin)/executive': typeof adminExecutiveRoute
  '/(admin)/gis': typeof adminGisRoute
  '/(admin)/intelligence': typeof adminIntelligenceRoute
  '/(admin)/markets': typeof adminMarketsRouteWithChildren
  '/(admin)/notices': typeof adminNoticesRoute
  '/(admin)/notifications': typeof adminNotificationsRoute
  '/(admin)/payments': typeof adminPaymentsRoute
  '/(admin)/reports': typeof adminReportsRoute
  '/(admin)/revenue-center': typeof adminRevenueCenterRoute
  '/(admin)/sanitation': typeof adminSanitationRoute
  '/(admin)/services': typeof adminServicesRoute
  '/(admin)/taxpayers': typeof adminTaxpayersRoute
  '/(admin)/transport': typeof adminTransportRoute
  '/(dashboard)/dashboard': typeof dashboardDashboardRoute
  '/(dashboard)/portal': typeof dashboardPortalRoute
  '/(public)/about': typeof publicAboutRoute
  '/(public)/contact': typeof publicContactRoute
  '/(public)/register': typeof publicRegisterRoute
  '/(public)/': typeof publicIndexRoute
  '/(admin)/markets/collect': typeof adminMarketsCollectRoute
  '/(admin)/markets/register': typeof adminMarketsRegisterRoute
  '/(admin)/markets/traders': typeof adminMarketsTradersRoute
  '/(auth)/auth/login': typeof authAuthLoginRoute
  '/(auth)/auth/signup': typeof authAuthSignupRoute
  '/(public)/properties/register': typeof publicPropertiesRegisterRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/(dashboard)/marshal/': typeof dashboardMarshalIndexRoute
  '/(dashboard)/officer/': typeof dashboardOfficerIndexRoute
  '/(public)/properties/': typeof publicPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/businesses'
    | '/bylaws'
    | '/command-center'
    | '/compliance'
    | '/executive'
    | '/gis'
    | '/intelligence'
    | '/markets'
    | '/notices'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/revenue-center'
    | '/sanitation'
    | '/services'
    | '/taxpayers'
    | '/transport'
    | '/dashboard'
    | '/portal'
    | '/about'
    | '/contact'
    | '/register'
    | '/'
    | '/markets/collect'
    | '/markets/register'
    | '/markets/traders'
    | '/auth/login'
    | '/auth/signup'
    | '/properties/register'
    | '/api/public/seed-demo'
    | '/marshal/'
    | '/officer/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/businesses'
    | '/bylaws'
    | '/command-center'
    | '/compliance'
    | '/executive'
    | '/gis'
    | '/intelligence'
    | '/markets'
    | '/notices'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/revenue-center'
    | '/sanitation'
    | '/services'
    | '/taxpayers'
    | '/transport'
    | '/dashboard'
    | '/portal'
    | '/about'
    | '/contact'
    | '/register'
    | '/'
    | '/markets/collect'
    | '/markets/register'
    | '/markets/traders'
    | '/auth/login'
    | '/auth/signup'
    | '/properties/register'
    | '/api/public/seed-demo'
    | '/marshal'
    | '/officer'
    | '/properties'
  id:
    | '__root__'
    | '/(admin)/businesses'
    | '/(admin)/bylaws'
    | '/(admin)/command-center'
    | '/(admin)/compliance'
    | '/(admin)/executive'
    | '/(admin)/gis'
    | '/(admin)/intelligence'
    | '/(admin)/markets'
    | '/(admin)/notices'
    | '/(admin)/notifications'
    | '/(admin)/payments'
    | '/(admin)/reports'
    | '/(admin)/revenue-center'
    | '/(admin)/sanitation'
    | '/(admin)/services'
    | '/(admin)/taxpayers'
    | '/(admin)/transport'
    | '/(dashboard)/dashboard'
    | '/(dashboard)/portal'
    | '/(public)/about'
    | '/(public)/contact'
    | '/(public)/register'
    | '/(public)/'
    | '/(admin)/markets/collect'
    | '/(admin)/markets/register'
    | '/(admin)/markets/traders'
    | '/(auth)/auth/login'
    | '/(auth)/auth/signup'
    | '/(public)/properties/register'
    | '/api/public/seed-demo'
    | '/(dashboard)/marshal/'
    | '/(dashboard)/officer/'
    | '/(public)/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminBusinessesRoute: typeof adminBusinessesRoute
  adminBylawsRoute: typeof adminBylawsRoute
  adminCommandCenterRoute: typeof adminCommandCenterRoute
  adminComplianceRoute: typeof adminComplianceRoute
  adminExecutiveRoute: typeof adminExecutiveRoute
  adminGisRoute: typeof adminGisRoute
  adminIntelligenceRoute: typeof adminIntelligenceRoute
  adminMarketsRoute: typeof adminMarketsRouteWithChildren
  adminNoticesRoute: typeof adminNoticesRoute
  adminNotificationsRoute: typeof adminNotificationsRoute
  adminPaymentsRoute: typeof adminPaymentsRoute
  adminReportsRoute: typeof adminReportsRoute
  adminRevenueCenterRoute: typeof adminRevenueCenterRoute
  adminSanitationRoute: typeof adminSanitationRoute
  adminServicesRoute: typeof adminServicesRoute
  adminTaxpayersRoute: typeof adminTaxpayersRoute
  adminTransportRoute: typeof adminTransportRoute
  dashboardDashboardRoute: typeof dashboardDashboardRoute
  dashboardPortalRoute: typeof dashboardPortalRoute
  publicAboutRoute: typeof publicAboutRoute
  publicContactRoute: typeof publicContactRoute
  publicRegisterRoute: typeof publicRegisterRoute
  publicIndexRoute: typeof publicIndexRoute
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
  publicPropertiesRegisterRoute: typeof publicPropertiesRegisterRoute
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
  dashboardMarshalIndexRoute: typeof dashboardMarshalIndexRoute
  dashboardOfficerIndexRoute: typeof dashboardOfficerIndexRoute
  publicPropertiesIndexRoute: typeof publicPropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/contact': {
      id: '/(public)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof publicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/portal': {
      id: '/(dashboard)/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof dashboardPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/transport': {
      id: '/(admin)/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof adminTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/taxpayers': {
      id: '/(admin)/taxpayers'
      path: '/taxpayers'
      fullPath: '/taxpayers'
      preLoaderRoute: typeof adminTaxpayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/services': {
      id: '/(admin)/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof adminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/sanitation': {
      id: '/(admin)/sanitation'
      path: '/sanitation'
      fullPath: '/sanitation'
      preLoaderRoute: typeof adminSanitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/revenue-center': {
      id: '/(admin)/revenue-center'
      path: '/revenue-center'
      fullPath: '/revenue-center'
      preLoaderRoute: typeof adminRevenueCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/reports': {
      id: '/(admin)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof adminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/payments': {
      id: '/(admin)/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof adminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/notifications': {
      id: '/(admin)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof adminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/notices': {
      id: '/(admin)/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof adminNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/markets': {
      id: '/(admin)/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof adminMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/intelligence': {
      id: '/(admin)/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof adminIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/gis': {
      id: '/(admin)/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof adminGisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/executive': {
      id: '/(admin)/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof adminExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/compliance': {
      id: '/(admin)/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof adminComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/command-center': {
      id: '/(admin)/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof adminCommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/bylaws': {
      id: '/(admin)/bylaws'
      path: '/bylaws'
      fullPath: '/bylaws'
      preLoaderRoute: typeof adminBylawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/businesses': {
      id: '/(admin)/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof adminBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/properties/': {
      id: '/(public)/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof publicPropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/officer/': {
      id: '/(dashboard)/officer/'
      path: '/officer'
      fullPath: '/officer/'
      preLoaderRoute: typeof dashboardOfficerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/marshal/': {
      id: '/(dashboard)/marshal/'
      path: '/marshal'
      fullPath: '/marshal/'
      preLoaderRoute: typeof dashboardMarshalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/properties/register': {
      id: '/(public)/properties/register'
      path: '/properties/register'
      fullPath: '/properties/register'
      preLoaderRoute: typeof publicPropertiesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/signup': {
      id: '/(auth)/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/login': {
      id: '/(auth)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/markets/traders': {
      id: '/(admin)/markets/traders'
      path: '/traders'
      fullPath: '/markets/traders'
      preLoaderRoute: typeof adminMarketsTradersRouteImport
      parentRoute: typeof adminMarketsRoute
    }
    '/(admin)/markets/register': {
      id: '/(admin)/markets/register'
      path: '/register'
      fullPath: '/markets/register'
      preLoaderRoute: typeof adminMarketsRegisterRouteImport
      parentRoute: typeof adminMarketsRoute
    }
    '/(admin)/markets/collect': {
      id: '/(admin)/markets/collect'
      path: '/collect'
      fullPath: '/markets/collect'
      preLoaderRoute: typeof adminMarketsCollectRouteImport
      parentRoute: typeof adminMarketsRoute
    }
  }
}

interface adminMarketsRouteChildren {
  adminMarketsCollectRoute: typeof adminMarketsCollectRoute
  adminMarketsRegisterRoute: typeof adminMarketsRegisterRoute
  adminMarketsTradersRoute: typeof adminMarketsTradersRoute
}

const adminMarketsRouteChildren: adminMarketsRouteChildren = {
  adminMarketsCollectRoute: adminMarketsCollectRoute,
  adminMarketsRegisterRoute: adminMarketsRegisterRoute,
  adminMarketsTradersRoute: adminMarketsTradersRoute,
}

const adminMarketsRouteWithChildren = adminMarketsRoute._addFileChildren(
  adminMarketsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminBusinessesRoute: adminBusinessesRoute,
  adminBylawsRoute: adminBylawsRoute,
  adminCommandCenterRoute: adminCommandCenterRoute,
  adminComplianceRoute: adminComplianceRoute,
  adminExecutiveRoute: adminExecutiveRoute,
  adminGisRoute: adminGisRoute,
  adminIntelligenceRoute: adminIntelligenceRoute,
  adminMarketsRoute: adminMarketsRouteWithChildren,
  adminNoticesRoute: adminNoticesRoute,
  adminNotificationsRoute: adminNotificationsRoute,
  adminPaymentsRoute: adminPaymentsRoute,
  adminReportsRoute: adminReportsRoute,
  adminRevenueCenterRoute: adminRevenueCenterRoute,
  adminSanitationRoute: adminSanitationRoute,
  adminServicesRoute: adminServicesRoute,
  adminTaxpayersRoute: adminTaxpayersRoute,
  adminTransportRoute: adminTransportRoute,
  dashboardDashboardRoute: dashboardDashboardRoute,
  dashboardPortalRoute: dashboardPortalRoute,
  publicAboutRoute: publicAboutRoute,
  publicContactRoute: publicContactRoute,
  publicRegisterRoute: publicRegisterRoute,
  publicIndexRoute: publicIndexRoute,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthSignupRoute: authAuthSignupRoute,
  publicPropertiesRegisterRoute: publicPropertiesRegisterRoute,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
  dashboardMarshalIndexRoute: dashboardMarshalIndexRoute,
  dashboardOfficerIndexRoute: dashboardOfficerIndexRoute,
  publicPropertiesIndexRoute: publicPropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
