/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as publicIndexRouteImport } from './../../routes/(public)/index'
import { Route as publicRegisterRouteImport } from './../../routes/(public)/register'
import { Route as publicPayRouteImport } from './../../routes/(public)/pay'
import { Route as publicContactRouteImport } from './../../routes/(public)/contact'
import { Route as publicAboutRouteImport } from './../../routes/(public)/about'
import { Route as dashboardPortalRouteImport } from './../../routes/(dashboard)/portal'
import { Route as dashboardDashboardRouteImport } from './../../routes/(dashboard)/dashboard'
import { Route as adminTransportRouteImport } from './../../routes/(admin)/transport'
import { Route as adminTaxpayersRouteImport } from './../../routes/(admin)/taxpayers'
import { Route as adminStaffRouteImport } from './../../routes/(admin)/staff'
import { Route as adminServicesRouteImport } from './../../routes/(admin)/services'
import { Route as adminSanitationRouteImport } from './../../routes/(admin)/sanitation'
import { Route as adminRevenueCenterRouteImport } from './../../routes/(admin)/revenue-center'
import { Route as adminReportsRouteImport } from './../../routes/(admin)/reports'
import { Route as adminPaymentsRouteImport } from './../../routes/(admin)/payments'
import { Route as adminNotificationsRouteImport } from './../../routes/(admin)/notifications'
import { Route as adminNoticesRouteImport } from './../../routes/(admin)/notices'
import { Route as adminMarketsRouteImport } from './../../routes/(admin)/markets'
import { Route as adminIntelligenceRouteImport } from './../../routes/(admin)/intelligence'
import { Route as adminGisRouteImport } from './../../routes/(admin)/gis'
import { Route as adminExecutiveRouteImport } from './../../routes/(admin)/executive'
import { Route as adminComplianceRouteImport } from './../../routes/(admin)/compliance'
import { Route as adminCommandCenterRouteImport } from './../../routes/(admin)/command-center'
import { Route as adminBylawsRouteImport } from './../../routes/(admin)/bylaws'
import { Route as adminBusinessesRouteImport } from './../../routes/(admin)/businesses'
import { Route as publicVerifyIndexRouteImport } from './../../routes/(public)/verify.index'
import { Route as publicPropertiesIndexRouteImport } from './../../routes/(public)/properties.index'
import { Route as dashboardOfficerIndexRouteImport } from './../../routes/(dashboard)/officer/index'
import { Route as dashboardMarshalIndexRouteImport } from './../../routes/(dashboard)/marshal/index'
import { Route as ApiPublicVerifyReceiptRouteImport } from './../../routes/api/public/verify-receipt'
import { Route as ApiPublicSeedDemoRouteImport } from './../../routes/api/public/seed-demo'
import { Route as ApiPublicPayReferenceRouteImport } from './../../routes/api/public/pay-reference'
import { Route as ApiPublicLookupRouteImport } from './../../routes/api/public/lookup'
import { Route as publicVerifyTokenRouteImport } from './../../routes/(public)/verify.$token'
import { Route as publicPropertiesRegisterRouteImport } from './../../routes/(public)/properties.register'
import { Route as authAuthSignupRouteImport } from './../../routes/(auth)/auth.signup'
import { Route as authAuthLoginRouteImport } from './../../routes/(auth)/auth.login'
import { Route as adminMarketsTradersRouteImport } from './../../routes/(admin)/markets.traders'
import { Route as adminMarketsRegisterRouteImport } from './../../routes/(admin)/markets.register'
import { Route as adminMarketsCollectRouteImport } from './../../routes/(admin)/markets.collect'
import { Route as adminExecutiveWardsRouteImport } from './../../routes/(admin)/executive.wards'
import { Route as adminExecutiveTransportRouteImport } from './../../routes/(admin)/executive.transport'
import { Route as adminExecutiveRevenueRouteImport } from './../../routes/(admin)/executive.revenue'
import { Route as adminExecutiveReportsRouteImport } from './../../routes/(admin)/executive.reports'
import { Route as adminExecutivePaymentsRouteImport } from './../../routes/(admin)/executive.payments'
import { Route as adminExecutiveNoticesRouteImport } from './../../routes/(admin)/executive.notices'
import { Route as adminExecutiveMarketsRouteImport } from './../../routes/(admin)/executive.markets'
import { Route as adminExecutiveIntelligenceRouteImport } from './../../routes/(admin)/executive.intelligence'
import { Route as adminExecutiveGisRouteImport } from './../../routes/(admin)/executive.gis'
import { Route as adminExecutiveEnforcementRouteImport } from './../../routes/(admin)/executive.enforcement'
import { Route as adminExecutiveComplianceRouteImport } from './../../routes/(admin)/executive.compliance'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRegisterRoute = publicRegisterRouteImport.update({
  id: '/(public)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPayRoute = publicPayRouteImport.update({
  id: '/(public)/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const publicContactRoute = publicContactRouteImport.update({
  id: '/(public)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/(public)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardPortalRoute = dashboardPortalRouteImport.update({
  id: '/(dashboard)/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const adminTransportRoute = adminTransportRouteImport.update({
  id: '/(admin)/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const adminTaxpayersRoute = adminTaxpayersRouteImport.update({
  id: '/(admin)/taxpayers',
  path: '/taxpayers',
  getParentRoute: () => rootRouteImport,
} as any)
const adminStaffRoute = adminStaffRouteImport.update({
  id: '/(admin)/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const adminServicesRoute = adminServicesRouteImport.update({
  id: '/(admin)/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSanitationRoute = adminSanitationRouteImport.update({
  id: '/(admin)/sanitation',
  path: '/sanitation',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRevenueCenterRoute = adminRevenueCenterRouteImport.update({
  id: '/(admin)/revenue-center',
  path: '/revenue-center',
  getParentRoute: () => rootRouteImport,
} as any)
const adminReportsRoute = adminReportsRouteImport.update({
  id: '/(admin)/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const adminPaymentsRoute = adminPaymentsRouteImport.update({
  id: '/(admin)/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const adminNotificationsRoute = adminNotificationsRouteImport.update({
  id: '/(admin)/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const adminNoticesRoute = adminNoticesRouteImport.update({
  id: '/(admin)/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const adminMarketsRoute = adminMarketsRouteImport.update({
  id: '/(admin)/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const adminIntelligenceRoute = adminIntelligenceRouteImport.update({
  id: '/(admin)/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const adminGisRoute = adminGisRouteImport.update({
  id: '/(admin)/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const adminExecutiveRoute = adminExecutiveRouteImport.update({
  id: '/(admin)/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const adminComplianceRoute = adminComplianceRouteImport.update({
  id: '/(admin)/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const adminCommandCenterRoute = adminCommandCenterRouteImport.update({
  id: '/(admin)/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const adminBylawsRoute = adminBylawsRouteImport.update({
  id: '/(admin)/bylaws',
  path: '/bylaws',
  getParentRoute: () => rootRouteImport,
} as any)
const adminBusinessesRoute = adminBusinessesRouteImport.update({
  id: '/(admin)/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const publicVerifyIndexRoute = publicVerifyIndexRouteImport.update({
  id: '/(public)/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPropertiesIndexRoute = publicPropertiesIndexRouteImport.update({
  id: '/(public)/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOfficerIndexRoute = dashboardOfficerIndexRouteImport.update({
  id: '/(dashboard)/officer/',
  path: '/officer/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardMarshalIndexRoute = dashboardMarshalIndexRouteImport.update({
  id: '/(dashboard)/marshal/',
  path: '/marshal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyReceiptRoute = ApiPublicVerifyReceiptRouteImport.update({
  id: '/api/public/verify-receipt',
  path: '/api/public/verify-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPayReferenceRoute = ApiPublicPayReferenceRouteImport.update({
  id: '/api/public/pay-reference',
  path: '/api/public/pay-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLookupRoute = ApiPublicLookupRouteImport.update({
  id: '/api/public/lookup',
  path: '/api/public/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const publicVerifyTokenRoute = publicVerifyTokenRouteImport.update({
  id: '/(public)/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPropertiesRegisterRoute =
  publicPropertiesRegisterRouteImport.update({
    id: '/(public)/properties/register',
    path: '/properties/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/(auth)/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/(auth)/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const adminMarketsTradersRoute = adminMarketsTradersRouteImport.update({
  id: '/traders',
  path: '/traders',
  getParentRoute: () => adminMarketsRoute,
} as any)
const adminMarketsRegisterRoute = adminMarketsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => adminMarketsRoute,
} as any)
const adminMarketsCollectRoute = adminMarketsCollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => adminMarketsRoute,
} as any)
const adminExecutiveWardsRoute = adminExecutiveWardsRouteImport.update({
  id: '/wards',
  path: '/wards',
  getParentRoute: () => adminExecutiveRoute,
} as any)
const adminExecutiveTransportRoute = adminExecutiveTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => adminExecutiveRoute,
} as any)
const adminExecutiveRevenueRoute = adminExecutiveRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => adminExecutiveRoute,
} as any)
const adminExecutiveReportsRoute = adminExecutiveReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => adminExecutiveRoute,
} as any)
const adminExecutivePaymentsRoute = adminExecutivePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => adminExecutiveRoute,
} as any)
const adminExecutiveNoticesRoute = adminExecutiveNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => adminExecutiveRoute,
} as any)
const adminExecutiveMarketsRoute = adminExecutiveMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => adminExecutiveRoute,
} as any)
const adminExecutiveIntelligenceRoute =
  adminExecutiveIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => adminExecutiveRoute,
  } as any)
const adminExecutiveGisRoute = adminExecutiveGisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => adminExecutiveRoute,
} as any)
const adminExecutiveEnforcementRoute =
  adminExecutiveEnforcementRouteImport.update({
    id: '/enforcement',
    path: '/enforcement',
    getParentRoute: () => adminExecutiveRoute,
  } as any)
const adminExecutiveComplianceRoute =
  adminExecutiveComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => adminExecutiveRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/businesses': typeof adminBusinessesRoute
  '/bylaws': typeof adminBylawsRoute
  '/command-center': typeof adminCommandCenterRoute
  '/compliance': typeof adminComplianceRoute
  '/executive': typeof adminExecutiveRouteWithChildren
  '/gis': typeof adminGisRoute
  '/intelligence': typeof adminIntelligenceRoute
  '/markets': typeof adminMarketsRouteWithChildren
  '/notices': typeof adminNoticesRoute
  '/notifications': typeof adminNotificationsRoute
  '/payments': typeof adminPaymentsRoute
  '/reports': typeof adminReportsRoute
  '/revenue-center': typeof adminRevenueCenterRoute
  '/sanitation': typeof adminSanitationRoute
  '/services': typeof adminServicesRoute
  '/staff': typeof adminStaffRoute
  '/taxpayers': typeof adminTaxpayersRoute
  '/transport': typeof adminTransportRoute
  '/dashboard': typeof dashboardDashboardRoute
  '/portal': typeof dashboardPortalRoute
  '/about': typeof publicAboutRoute
  '/contact': typeof publicContactRoute
  '/pay': typeof publicPayRoute
  '/register': typeof publicRegisterRoute
  '/': typeof publicIndexRoute
  '/executive/compliance': typeof adminExecutiveComplianceRoute
  '/executive/enforcement': typeof adminExecutiveEnforcementRoute
  '/executive/gis': typeof adminExecutiveGisRoute
  '/executive/intelligence': typeof adminExecutiveIntelligenceRoute
  '/executive/markets': typeof adminExecutiveMarketsRoute
  '/executive/notices': typeof adminExecutiveNoticesRoute
  '/executive/payments': typeof adminExecutivePaymentsRoute
  '/executive/reports': typeof adminExecutiveReportsRoute
  '/executive/revenue': typeof adminExecutiveRevenueRoute
  '/executive/transport': typeof adminExecutiveTransportRoute
  '/executive/wards': typeof adminExecutiveWardsRoute
  '/markets/collect': typeof adminMarketsCollectRoute
  '/markets/register': typeof adminMarketsRegisterRoute
  '/markets/traders': typeof adminMarketsTradersRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/properties/register': typeof publicPropertiesRegisterRoute
  '/verify/$token': typeof publicVerifyTokenRoute
  '/api/public/lookup': typeof ApiPublicLookupRoute
  '/api/public/pay-reference': typeof ApiPublicPayReferenceRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/api/public/verify-receipt': typeof ApiPublicVerifyReceiptRoute
  '/marshal/': typeof dashboardMarshalIndexRoute
  '/officer/': typeof dashboardOfficerIndexRoute
  '/properties/': typeof publicPropertiesIndexRoute
  '/verify/': typeof publicVerifyIndexRoute
}
export interface FileRoutesByTo {
  '/businesses': typeof adminBusinessesRoute
  '/bylaws': typeof adminBylawsRoute
  '/command-center': typeof adminCommandCenterRoute
  '/compliance': typeof adminComplianceRoute
  '/executive': typeof adminExecutiveRouteWithChildren
  '/gis': typeof adminGisRoute
  '/intelligence': typeof adminIntelligenceRoute
  '/markets': typeof adminMarketsRouteWithChildren
  '/notices': typeof adminNoticesRoute
  '/notifications': typeof adminNotificationsRoute
  '/payments': typeof adminPaymentsRoute
  '/reports': typeof adminReportsRoute
  '/revenue-center': typeof adminRevenueCenterRoute
  '/sanitation': typeof adminSanitationRoute
  '/services': typeof adminServicesRoute
  '/staff': typeof adminStaffRoute
  '/taxpayers': typeof adminTaxpayersRoute
  '/transport': typeof adminTransportRoute
  '/dashboard': typeof dashboardDashboardRoute
  '/portal': typeof dashboardPortalRoute
  '/about': typeof publicAboutRoute
  '/contact': typeof publicContactRoute
  '/pay': typeof publicPayRoute
  '/register': typeof publicRegisterRoute
  '/': typeof publicIndexRoute
  '/executive/compliance': typeof adminExecutiveComplianceRoute
  '/executive/enforcement': typeof adminExecutiveEnforcementRoute
  '/executive/gis': typeof adminExecutiveGisRoute
  '/executive/intelligence': typeof adminExecutiveIntelligenceRoute
  '/executive/markets': typeof adminExecutiveMarketsRoute
  '/executive/notices': typeof adminExecutiveNoticesRoute
  '/executive/payments': typeof adminExecutivePaymentsRoute
  '/executive/reports': typeof adminExecutiveReportsRoute
  '/executive/revenue': typeof adminExecutiveRevenueRoute
  '/executive/transport': typeof adminExecutiveTransportRoute
  '/executive/wards': typeof adminExecutiveWardsRoute
  '/markets/collect': typeof adminMarketsCollectRoute
  '/markets/register': typeof adminMarketsRegisterRoute
  '/markets/traders': typeof adminMarketsTradersRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/properties/register': typeof publicPropertiesRegisterRoute
  '/verify/$token': typeof publicVerifyTokenRoute
  '/api/public/lookup': typeof ApiPublicLookupRoute
  '/api/public/pay-reference': typeof ApiPublicPayReferenceRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/api/public/verify-receipt': typeof ApiPublicVerifyReceiptRoute
  '/marshal': typeof dashboardMarshalIndexRoute
  '/officer': typeof dashboardOfficerIndexRoute
  '/properties': typeof publicPropertiesIndexRoute
  '/verify': typeof publicVerifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)/businesses': typeof adminBusinessesRoute
  '/(admin)/bylaws': typeof adminBylawsRoute
  '/(admin)/command-center': typeof adminCommandCenterRoute
  '/(admin)/compliance': typeof adminComplianceRoute
  '/(admin)/executive': typeof adminExecutiveRouteWithChildren
  '/(admin)/gis': typeof adminGisRoute
  '/(admin)/intelligence': typeof adminIntelligenceRoute
  '/(admin)/markets': typeof adminMarketsRouteWithChildren
  '/(admin)/notices': typeof adminNoticesRoute
  '/(admin)/notifications': typeof adminNotificationsRoute
  '/(admin)/payments': typeof adminPaymentsRoute
  '/(admin)/reports': typeof adminReportsRoute
  '/(admin)/revenue-center': typeof adminRevenueCenterRoute
  '/(admin)/sanitation': typeof adminSanitationRoute
  '/(admin)/services': typeof adminServicesRoute
  '/(admin)/staff': typeof adminStaffRoute
  '/(admin)/taxpayers': typeof adminTaxpayersRoute
  '/(admin)/transport': typeof adminTransportRoute
  '/(dashboard)/dashboard': typeof dashboardDashboardRoute
  '/(dashboard)/portal': typeof dashboardPortalRoute
  '/(public)/about': typeof publicAboutRoute
  '/(public)/contact': typeof publicContactRoute
  '/(public)/pay': typeof publicPayRoute
  '/(public)/register': typeof publicRegisterRoute
  '/(public)/': typeof publicIndexRoute
  '/(admin)/executive/compliance': typeof adminExecutiveComplianceRoute
  '/(admin)/executive/enforcement': typeof adminExecutiveEnforcementRoute
  '/(admin)/executive/gis': typeof adminExecutiveGisRoute
  '/(admin)/executive/intelligence': typeof adminExecutiveIntelligenceRoute
  '/(admin)/executive/markets': typeof adminExecutiveMarketsRoute
  '/(admin)/executive/notices': typeof adminExecutiveNoticesRoute
  '/(admin)/executive/payments': typeof adminExecutivePaymentsRoute
  '/(admin)/executive/reports': typeof adminExecutiveReportsRoute
  '/(admin)/executive/revenue': typeof adminExecutiveRevenueRoute
  '/(admin)/executive/transport': typeof adminExecutiveTransportRoute
  '/(admin)/executive/wards': typeof adminExecutiveWardsRoute
  '/(admin)/markets/collect': typeof adminMarketsCollectRoute
  '/(admin)/markets/register': typeof adminMarketsRegisterRoute
  '/(admin)/markets/traders': typeof adminMarketsTradersRoute
  '/(auth)/auth/login': typeof authAuthLoginRoute
  '/(auth)/auth/signup': typeof authAuthSignupRoute
  '/(public)/properties/register': typeof publicPropertiesRegisterRoute
  '/(public)/verify/$token': typeof publicVerifyTokenRoute
  '/api/public/lookup': typeof ApiPublicLookupRoute
  '/api/public/pay-reference': typeof ApiPublicPayReferenceRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/api/public/verify-receipt': typeof ApiPublicVerifyReceiptRoute
  '/(dashboard)/marshal/': typeof dashboardMarshalIndexRoute
  '/(dashboard)/officer/': typeof dashboardOfficerIndexRoute
  '/(public)/properties/': typeof publicPropertiesIndexRoute
  '/(public)/verify/': typeof publicVerifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/businesses'
    | '/bylaws'
    | '/command-center'
    | '/compliance'
    | '/executive'
    | '/gis'
    | '/intelligence'
    | '/markets'
    | '/notices'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/revenue-center'
    | '/sanitation'
    | '/services'
    | '/staff'
    | '/taxpayers'
    | '/transport'
    | '/dashboard'
    | '/portal'
    | '/about'
    | '/contact'
    | '/pay'
    | '/register'
    | '/'
    | '/executive/compliance'
    | '/executive/enforcement'
    | '/executive/gis'
    | '/executive/intelligence'
    | '/executive/markets'
    | '/executive/notices'
    | '/executive/payments'
    | '/executive/reports'
    | '/executive/revenue'
    | '/executive/transport'
    | '/executive/wards'
    | '/markets/collect'
    | '/markets/register'
    | '/markets/traders'
    | '/auth/login'
    | '/auth/signup'
    | '/properties/register'
    | '/verify/$token'
    | '/api/public/lookup'
    | '/api/public/pay-reference'
    | '/api/public/seed-demo'
    | '/api/public/verify-receipt'
    | '/marshal/'
    | '/officer/'
    | '/properties/'
    | '/verify/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/businesses'
    | '/bylaws'
    | '/command-center'
    | '/compliance'
    | '/executive'
    | '/gis'
    | '/intelligence'
    | '/markets'
    | '/notices'
    | '/notifications'
    | '/payments'
    | '/reports'
    | '/revenue-center'
    | '/sanitation'
    | '/services'
    | '/staff'
    | '/taxpayers'
    | '/transport'
    | '/dashboard'
    | '/portal'
    | '/about'
    | '/contact'
    | '/pay'
    | '/register'
    | '/'
    | '/executive/compliance'
    | '/executive/enforcement'
    | '/executive/gis'
    | '/executive/intelligence'
    | '/executive/markets'
    | '/executive/notices'
    | '/executive/payments'
    | '/executive/reports'
    | '/executive/revenue'
    | '/executive/transport'
    | '/executive/wards'
    | '/markets/collect'
    | '/markets/register'
    | '/markets/traders'
    | '/auth/login'
    | '/auth/signup'
    | '/properties/register'
    | '/verify/$token'
    | '/api/public/lookup'
    | '/api/public/pay-reference'
    | '/api/public/seed-demo'
    | '/api/public/verify-receipt'
    | '/marshal'
    | '/officer'
    | '/properties'
    | '/verify'
  id:
    | '__root__'
    | '/(admin)/businesses'
    | '/(admin)/bylaws'
    | '/(admin)/command-center'
    | '/(admin)/compliance'
    | '/(admin)/executive'
    | '/(admin)/gis'
    | '/(admin)/intelligence'
    | '/(admin)/markets'
    | '/(admin)/notices'
    | '/(admin)/notifications'
    | '/(admin)/payments'
    | '/(admin)/reports'
    | '/(admin)/revenue-center'
    | '/(admin)/sanitation'
    | '/(admin)/services'
    | '/(admin)/staff'
    | '/(admin)/taxpayers'
    | '/(admin)/transport'
    | '/(dashboard)/dashboard'
    | '/(dashboard)/portal'
    | '/(public)/about'
    | '/(public)/contact'
    | '/(public)/pay'
    | '/(public)/register'
    | '/(public)/'
    | '/(admin)/executive/compliance'
    | '/(admin)/executive/enforcement'
    | '/(admin)/executive/gis'
    | '/(admin)/executive/intelligence'
    | '/(admin)/executive/markets'
    | '/(admin)/executive/notices'
    | '/(admin)/executive/payments'
    | '/(admin)/executive/reports'
    | '/(admin)/executive/revenue'
    | '/(admin)/executive/transport'
    | '/(admin)/executive/wards'
    | '/(admin)/markets/collect'
    | '/(admin)/markets/register'
    | '/(admin)/markets/traders'
    | '/(auth)/auth/login'
    | '/(auth)/auth/signup'
    | '/(public)/properties/register'
    | '/(public)/verify/$token'
    | '/api/public/lookup'
    | '/api/public/pay-reference'
    | '/api/public/seed-demo'
    | '/api/public/verify-receipt'
    | '/(dashboard)/marshal/'
    | '/(dashboard)/officer/'
    | '/(public)/properties/'
    | '/(public)/verify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminBusinessesRoute: typeof adminBusinessesRoute
  adminBylawsRoute: typeof adminBylawsRoute
  adminCommandCenterRoute: typeof adminCommandCenterRoute
  adminComplianceRoute: typeof adminComplianceRoute
  adminExecutiveRoute: typeof adminExecutiveRouteWithChildren
  adminGisRoute: typeof adminGisRoute
  adminIntelligenceRoute: typeof adminIntelligenceRoute
  adminMarketsRoute: typeof adminMarketsRouteWithChildren
  adminNoticesRoute: typeof adminNoticesRoute
  adminNotificationsRoute: typeof adminNotificationsRoute
  adminPaymentsRoute: typeof adminPaymentsRoute
  adminReportsRoute: typeof adminReportsRoute
  adminRevenueCenterRoute: typeof adminRevenueCenterRoute
  adminSanitationRoute: typeof adminSanitationRoute
  adminServicesRoute: typeof adminServicesRoute
  adminStaffRoute: typeof adminStaffRoute
  adminTaxpayersRoute: typeof adminTaxpayersRoute
  adminTransportRoute: typeof adminTransportRoute
  dashboardDashboardRoute: typeof dashboardDashboardRoute
  dashboardPortalRoute: typeof dashboardPortalRoute
  publicAboutRoute: typeof publicAboutRoute
  publicContactRoute: typeof publicContactRoute
  publicPayRoute: typeof publicPayRoute
  publicRegisterRoute: typeof publicRegisterRoute
  publicIndexRoute: typeof publicIndexRoute
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
  publicPropertiesRegisterRoute: typeof publicPropertiesRegisterRoute
  publicVerifyTokenRoute: typeof publicVerifyTokenRoute
  ApiPublicLookupRoute: typeof ApiPublicLookupRoute
  ApiPublicPayReferenceRoute: typeof ApiPublicPayReferenceRoute
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
  ApiPublicVerifyReceiptRoute: typeof ApiPublicVerifyReceiptRoute
  dashboardMarshalIndexRoute: typeof dashboardMarshalIndexRoute
  dashboardOfficerIndexRoute: typeof dashboardOfficerIndexRoute
  publicPropertiesIndexRoute: typeof publicPropertiesIndexRoute
  publicVerifyIndexRoute: typeof publicVerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/pay': {
      id: '/(public)/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof publicPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/contact': {
      id: '/(public)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof publicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/portal': {
      id: '/(dashboard)/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof dashboardPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/transport': {
      id: '/(admin)/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof adminTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/taxpayers': {
      id: '/(admin)/taxpayers'
      path: '/taxpayers'
      fullPath: '/taxpayers'
      preLoaderRoute: typeof adminTaxpayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/staff': {
      id: '/(admin)/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof adminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/services': {
      id: '/(admin)/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof adminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/sanitation': {
      id: '/(admin)/sanitation'
      path: '/sanitation'
      fullPath: '/sanitation'
      preLoaderRoute: typeof adminSanitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/revenue-center': {
      id: '/(admin)/revenue-center'
      path: '/revenue-center'
      fullPath: '/revenue-center'
      preLoaderRoute: typeof adminRevenueCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/reports': {
      id: '/(admin)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof adminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/payments': {
      id: '/(admin)/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof adminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/notifications': {
      id: '/(admin)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof adminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/notices': {
      id: '/(admin)/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof adminNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/markets': {
      id: '/(admin)/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof adminMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/intelligence': {
      id: '/(admin)/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof adminIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/gis': {
      id: '/(admin)/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof adminGisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/executive': {
      id: '/(admin)/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof adminExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/compliance': {
      id: '/(admin)/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof adminComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/command-center': {
      id: '/(admin)/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof adminCommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/bylaws': {
      id: '/(admin)/bylaws'
      path: '/bylaws'
      fullPath: '/bylaws'
      preLoaderRoute: typeof adminBylawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/businesses': {
      id: '/(admin)/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof adminBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/verify/': {
      id: '/(public)/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof publicVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/properties/': {
      id: '/(public)/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof publicPropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/officer/': {
      id: '/(dashboard)/officer/'
      path: '/officer'
      fullPath: '/officer/'
      preLoaderRoute: typeof dashboardOfficerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/marshal/': {
      id: '/(dashboard)/marshal/'
      path: '/marshal'
      fullPath: '/marshal/'
      preLoaderRoute: typeof dashboardMarshalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-receipt': {
      id: '/api/public/verify-receipt'
      path: '/api/public/verify-receipt'
      fullPath: '/api/public/verify-receipt'
      preLoaderRoute: typeof ApiPublicVerifyReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pay-reference': {
      id: '/api/public/pay-reference'
      path: '/api/public/pay-reference'
      fullPath: '/api/public/pay-reference'
      preLoaderRoute: typeof ApiPublicPayReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lookup': {
      id: '/api/public/lookup'
      path: '/api/public/lookup'
      fullPath: '/api/public/lookup'
      preLoaderRoute: typeof ApiPublicLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/verify/$token': {
      id: '/(public)/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof publicVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/properties/register': {
      id: '/(public)/properties/register'
      path: '/properties/register'
      fullPath: '/properties/register'
      preLoaderRoute: typeof publicPropertiesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/signup': {
      id: '/(auth)/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/login': {
      id: '/(auth)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/markets/traders': {
      id: '/(admin)/markets/traders'
      path: '/traders'
      fullPath: '/markets/traders'
      preLoaderRoute: typeof adminMarketsTradersRouteImport
      parentRoute: typeof adminMarketsRoute
    }
    '/(admin)/markets/register': {
      id: '/(admin)/markets/register'
      path: '/register'
      fullPath: '/markets/register'
      preLoaderRoute: typeof adminMarketsRegisterRouteImport
      parentRoute: typeof adminMarketsRoute
    }
    '/(admin)/markets/collect': {
      id: '/(admin)/markets/collect'
      path: '/collect'
      fullPath: '/markets/collect'
      preLoaderRoute: typeof adminMarketsCollectRouteImport
      parentRoute: typeof adminMarketsRoute
    }
    '/(admin)/executive/wards': {
      id: '/(admin)/executive/wards'
      path: '/wards'
      fullPath: '/executive/wards'
      preLoaderRoute: typeof adminExecutiveWardsRouteImport
      parentRoute: typeof adminExecutiveRoute
    }
    '/(admin)/executive/transport': {
      id: '/(admin)/executive/transport'
      path: '/transport'
      fullPath: '/executive/transport'
      preLoaderRoute: typeof adminExecutiveTransportRouteImport
      parentRoute: typeof adminExecutiveRoute
    }
    '/(admin)/executive/revenue': {
      id: '/(admin)/executive/revenue'
      path: '/revenue'
      fullPath: '/executive/revenue'
      preLoaderRoute: typeof adminExecutiveRevenueRouteImport
      parentRoute: typeof adminExecutiveRoute
    }
    '/(admin)/executive/reports': {
      id: '/(admin)/executive/reports'
      path: '/reports'
      fullPath: '/executive/reports'
      preLoaderRoute: typeof adminExecutiveReportsRouteImport
      parentRoute: typeof adminExecutiveRoute
    }
    '/(admin)/executive/payments': {
      id: '/(admin)/executive/payments'
      path: '/payments'
      fullPath: '/executive/payments'
      preLoaderRoute: typeof adminExecutivePaymentsRouteImport
      parentRoute: typeof adminExecutiveRoute
    }
    '/(admin)/executive/notices': {
      id: '/(admin)/executive/notices'
      path: '/notices'
      fullPath: '/executive/notices'
      preLoaderRoute: typeof adminExecutiveNoticesRouteImport
      parentRoute: typeof adminExecutiveRoute
    }
    '/(admin)/executive/markets': {
      id: '/(admin)/executive/markets'
      path: '/markets'
      fullPath: '/executive/markets'
      preLoaderRoute: typeof adminExecutiveMarketsRouteImport
      parentRoute: typeof adminExecutiveRoute
    }
    '/(admin)/executive/intelligence': {
      id: '/(admin)/executive/intelligence'
      path: '/intelligence'
      fullPath: '/executive/intelligence'
      preLoaderRoute: typeof adminExecutiveIntelligenceRouteImport
      parentRoute: typeof adminExecutiveRoute
    }
    '/(admin)/executive/gis': {
      id: '/(admin)/executive/gis'
      path: '/gis'
      fullPath: '/executive/gis'
      preLoaderRoute: typeof adminExecutiveGisRouteImport
      parentRoute: typeof adminExecutiveRoute
    }
    '/(admin)/executive/enforcement': {
      id: '/(admin)/executive/enforcement'
      path: '/enforcement'
      fullPath: '/executive/enforcement'
      preLoaderRoute: typeof adminExecutiveEnforcementRouteImport
      parentRoute: typeof adminExecutiveRoute
    }
    '/(admin)/executive/compliance': {
      id: '/(admin)/executive/compliance'
      path: '/compliance'
      fullPath: '/executive/compliance'
      preLoaderRoute: typeof adminExecutiveComplianceRouteImport
      parentRoute: typeof adminExecutiveRoute
    }
  }
}

interface adminExecutiveRouteChildren {
  adminExecutiveComplianceRoute: typeof adminExecutiveComplianceRoute
  adminExecutiveEnforcementRoute: typeof adminExecutiveEnforcementRoute
  adminExecutiveGisRoute: typeof adminExecutiveGisRoute
  adminExecutiveIntelligenceRoute: typeof adminExecutiveIntelligenceRoute
  adminExecutiveMarketsRoute: typeof adminExecutiveMarketsRoute
  adminExecutiveNoticesRoute: typeof adminExecutiveNoticesRoute
  adminExecutivePaymentsRoute: typeof adminExecutivePaymentsRoute
  adminExecutiveReportsRoute: typeof adminExecutiveReportsRoute
  adminExecutiveRevenueRoute: typeof adminExecutiveRevenueRoute
  adminExecutiveTransportRoute: typeof adminExecutiveTransportRoute
  adminExecutiveWardsRoute: typeof adminExecutiveWardsRoute
}

const adminExecutiveRouteChildren: adminExecutiveRouteChildren = {
  adminExecutiveComplianceRoute: adminExecutiveComplianceRoute,
  adminExecutiveEnforcementRoute: adminExecutiveEnforcementRoute,
  adminExecutiveGisRoute: adminExecutiveGisRoute,
  adminExecutiveIntelligenceRoute: adminExecutiveIntelligenceRoute,
  adminExecutiveMarketsRoute: adminExecutiveMarketsRoute,
  adminExecutiveNoticesRoute: adminExecutiveNoticesRoute,
  adminExecutivePaymentsRoute: adminExecutivePaymentsRoute,
  adminExecutiveReportsRoute: adminExecutiveReportsRoute,
  adminExecutiveRevenueRoute: adminExecutiveRevenueRoute,
  adminExecutiveTransportRoute: adminExecutiveTransportRoute,
  adminExecutiveWardsRoute: adminExecutiveWardsRoute,
}

const adminExecutiveRouteWithChildren = adminExecutiveRoute._addFileChildren(
  adminExecutiveRouteChildren,
)

interface adminMarketsRouteChildren {
  adminMarketsCollectRoute: typeof adminMarketsCollectRoute
  adminMarketsRegisterRoute: typeof adminMarketsRegisterRoute
  adminMarketsTradersRoute: typeof adminMarketsTradersRoute
}

const adminMarketsRouteChildren: adminMarketsRouteChildren = {
  adminMarketsCollectRoute: adminMarketsCollectRoute,
  adminMarketsRegisterRoute: adminMarketsRegisterRoute,
  adminMarketsTradersRoute: adminMarketsTradersRoute,
}

const adminMarketsRouteWithChildren = adminMarketsRoute._addFileChildren(
  adminMarketsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminBusinessesRoute: adminBusinessesRoute,
  adminBylawsRoute: adminBylawsRoute,
  adminCommandCenterRoute: adminCommandCenterRoute,
  adminComplianceRoute: adminComplianceRoute,
  adminExecutiveRoute: adminExecutiveRouteWithChildren,
  adminGisRoute: adminGisRoute,
  adminIntelligenceRoute: adminIntelligenceRoute,
  adminMarketsRoute: adminMarketsRouteWithChildren,
  adminNoticesRoute: adminNoticesRoute,
  adminNotificationsRoute: adminNotificationsRoute,
  adminPaymentsRoute: adminPaymentsRoute,
  adminReportsRoute: adminReportsRoute,
  adminRevenueCenterRoute: adminRevenueCenterRoute,
  adminSanitationRoute: adminSanitationRoute,
  adminServicesRoute: adminServicesRoute,
  adminStaffRoute: adminStaffRoute,
  adminTaxpayersRoute: adminTaxpayersRoute,
  adminTransportRoute: adminTransportRoute,
  dashboardDashboardRoute: dashboardDashboardRoute,
  dashboardPortalRoute: dashboardPortalRoute,
  publicAboutRoute: publicAboutRoute,
  publicContactRoute: publicContactRoute,
  publicPayRoute: publicPayRoute,
  publicRegisterRoute: publicRegisterRoute,
  publicIndexRoute: publicIndexRoute,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthSignupRoute: authAuthSignupRoute,
  publicPropertiesRegisterRoute: publicPropertiesRegisterRoute,
  publicVerifyTokenRoute: publicVerifyTokenRoute,
  ApiPublicLookupRoute: ApiPublicLookupRoute,
  ApiPublicPayReferenceRoute: ApiPublicPayReferenceRoute,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
  ApiPublicVerifyReceiptRoute: ApiPublicVerifyReceiptRoute,
  dashboardMarshalIndexRoute: dashboardMarshalIndexRoute,
  dashboardOfficerIndexRoute: dashboardOfficerIndexRoute,
  publicPropertiesIndexRoute: publicPropertiesIndexRoute,
  publicVerifyIndexRoute: publicVerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
