/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SanitationRouteImport } from './routes/sanitation'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BylawsRouteImport } from './routes/bylaws'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesRegisterRouteImport } from './routes/properties.register'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SanitationRoute = SanitationRouteImport.update({
  id: '/sanitation',
  path: '/sanitation',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BylawsRoute = BylawsRouteImport.update({
  id: '/bylaws',
  path: '/bylaws',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRegisterRoute = PropertiesRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PropertiesRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bylaws': typeof BylawsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/payments': typeof PaymentsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sanitation': typeof SanitationRoute
  '/services': typeof ServicesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/properties/register': typeof PropertiesRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bylaws': typeof BylawsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/payments': typeof PaymentsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sanitation': typeof SanitationRoute
  '/services': typeof ServicesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/properties/register': typeof PropertiesRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bylaws': typeof BylawsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/payments': typeof PaymentsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sanitation': typeof SanitationRoute
  '/services': typeof ServicesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/properties/register': typeof PropertiesRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bylaws'
    | '/contact'
    | '/dashboard'
    | '/payments'
    | '/properties'
    | '/sanitation'
    | '/services'
    | '/auth/login'
    | '/auth/signup'
    | '/properties/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bylaws'
    | '/contact'
    | '/dashboard'
    | '/payments'
    | '/properties'
    | '/sanitation'
    | '/services'
    | '/auth/login'
    | '/auth/signup'
    | '/properties/register'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bylaws'
    | '/contact'
    | '/dashboard'
    | '/payments'
    | '/properties'
    | '/sanitation'
    | '/services'
    | '/auth/login'
    | '/auth/signup'
    | '/properties/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BylawsRoute: typeof BylawsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  PaymentsRoute: typeof PaymentsRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  SanitationRoute: typeof SanitationRoute
  ServicesRoute: typeof ServicesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanitation': {
      id: '/sanitation'
      path: '/sanitation'
      fullPath: '/sanitation'
      preLoaderRoute: typeof SanitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bylaws': {
      id: '/bylaws'
      path: '/bylaws'
      fullPath: '/bylaws'
      preLoaderRoute: typeof BylawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/register': {
      id: '/properties/register'
      path: '/register'
      fullPath: '/properties/register'
      preLoaderRoute: typeof PropertiesRegisterRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PropertiesRouteChildren {
  PropertiesRegisterRoute: typeof PropertiesRegisterRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesRegisterRoute: PropertiesRegisterRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BylawsRoute: BylawsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  PaymentsRoute: PaymentsRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  SanitationRoute: SanitationRoute,
  ServicesRoute: ServicesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
